version: '3.8'

services:
  assistant:
    build: .
    ports:
      - 3003:3003
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.assistant-service.loadbalancer.server.port=80"
      # http
      - "traefik.http.routers.assistant.entrypoints=web"
      - "traefik.http.routers.assistant.rule=PathPrefix(`/`)"
      - "traefik.http.routers.assistant.service=assistant-service"
    volumes:
      - ./docs:/app/docs
    environment:
      - OPENAI_API_KEY
